### PR TITLE
Fixed issue in Homepage UI

### PR DESCRIPTION
**Pull request by Mudasir7-Prof-Snape**

### CODE REVIEW

**Comment by koalalu007** [comment]
provide photo before and after making changes

**Comment by Mudasir7-Prof-Snape** [comment]
@koalalu007 sir i provided photos in issue #29 please consider it and accept this PR

**Comment by Mudasir7-Prof-Snape** [comment]
after changes
Screenshot (67)

**Review by gaurovgiri — CHANGES_REQUESTED** [review]
Thank you for your contribution. But the color combination looks off.

**Comment by Mudasir7-Prof-Snape** [comment]
@gaurovgiri Hope this work out!
Screenshot (77)
I did these changes in index.css

**Pull request closed without merging**
