### PR TITLE
fixes: #16 Modify the input types for Email, Phone, and Dates

### PR DESCRIPTION
**Pull request by THEFZNKHAN**
fixes The #16 issue.
Modify the input types for Emails, Phone numbers, and Dates for better user experience.

### CODE REVIEW

**Comment by THEFZNKHAN** [comment]
Would you please add the "HACKTOBERFEST-ACCEPTED" label to my PR.

**Review by koalalu007 — COMMENTED** [review]
provide photo before and after change

**Comment by koalalu007** [comment]
resolve conflict!

**Comment by THEFZNKHAN** [comment]
Sorry for late 
here is the screenshot.
Before:
Screenshot 2023-10-04 175311

After:
Screenshot 2023-10-04 175625

**Comment by THEFZNKHAN** [comment]
Please let me know if anything needs to change.

**Review by gaurovgiri — APPROVED** [review]
Looks good to me!

**Pull request closed without merging**
